title: 乐趣为王
author: BH1RIO
description: 博客八世
url: https://just4fun.cn
base: 
permalink: /:year/:month/:day/:title:output_ext
markdown: GFM
theme: minima
twitter_username: fatiao
github_username:  bh1rio
rss: rss
show_excerpts: true
minima:
  skin: class

 # _pages
include: ['_pages']